### ISSUE TITLE
How can I get the same results in every training?

### ISSUE THREAD

**Issue by linhaojia13** [mit-han-lab/pvcnn#14]
Hi, thank you for your impressive works!
I noticed that you set the cudnn.benchmark false,
`cudnn.benchmark = False`
and fixed the random seed:
`    seed = configs.seed`
     `random.seed(seed)`
    `np.random.seed(seed)`
    `torch.manual_seed(seed)`
I add another line:
`    torch.cuda.manual_seed_all(seed)`

However, these counldn't keep the results same in every training. How can I get the same results in every training?

**Comment by synxlin** [comment]
Hi, @linhaojia13. Sorry for the late response.
`torch.manual_seed(seed)` will automatically call `torch.cuda.manual_seed_all(seed)` if CUDA environment is detected.
Setting `seed` can only help keep the evaluation results almost the same. It might be difficult to keep the training the same, since some operations we written in CUDA may introduce some random into training which is not controlled by setting seed in the python side.

**Comment by synxlin** [comment]
I will close the issue for now. Feel free to re-open if you have further problems.
