### ISSUE TITLE
Testing Pretrained Models Error

### ISSUE THREAD

**Issue by Jacky-gsq** [mit-han-lab/pvcnn#6]
thank you for the code!
but i got the error as follows  when running 
"python train.py configs/kitti/frustum/pvcnne.py --devices 0 --evaluate --configs.evaluate.best_checkpoint_path kitti.frustum.pvcnne.pth.tar --configs.evaluate.num_tests [#measurements]"

Error:
==> loading configs from ['configs/kitti/frustum/pvcnne.py']
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    main()
  File "train.py", line 81, in main
    configs.evaluate.fn(configs)
  File "/root/jacky/pvcnn/evaluate/kitti/frustum/eval.py", line 85, in evaluate
    if  configs.evaluate.num_tests > 1:
TypeError: '>' not supported between instances of 'str' and 'int'

by the way, i'm confused about the "[#measurements]" at the end of code.
could you explain it ? thanks again.

**Comment by synxlin** [comment]
Hi, @Jacky-gsq. You should replace the [#measurements] with the int number you want. For example, if you want to evaluate the model 20 times, the command should be,
```
python train.py configs/kitti/frustum/pvcnne.py --devices 0 --evaluate --configs.evaluate.best_checkpoint_path kitti.frustum.pvcnne.pth.tar --configs.evaluate.num_tests 20
```
Since Frustum-PointNet/PointNet++ backbone randomly samples the points, the evaluation accuracy will fluctuate. In order to eliminate the effects, one can evaluate multiple times to find out the average performance. Our code also prints out the performance of each evaluation so that you can find the best performance.

**Comment by Jacky-gsq** [comment]
@synxlin thank you! it works.
